spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: FileUploadMS
          uri: lb://FileUploadMS
          predicates:
            - Path=/fileUpload/success
